### ISSUE TITLE
Error 406 when downloading notMNIST dataset chapter 2.

### ISSUE THREAD

**Issue by tails1234** [mlwithtf/mlwithtf#5]
There is an error returned from the urls of the notMNIST dataset, when running download.py inside chapter_02 folder.

> Traceback (most recent call last):
>   File "download.py", line 7, in <module>
>     dataset, image_size, num_of_classes, num_of_channels = data_utils.prepare_not_mnist_dataset(root_dir="..")
>   File "/home/tails/MLTF1_ex/MLwithTF/data_utils.py", line 416, in prepare_not_mnist_dataset
>     train_file_path = download_file(training_set_url, dataset_path, train_download_size)
>   File "/home/tails/MLTF1_ex/MLwithTF/data_utils.py", line 48, in download_file
>     filename, _ = urlretrieve(file_url, file_output_path, download_hook_function)
>   File "/home/tails/anaconda3/envs/env37/lib/python3.7/urllib/request.py", line 247, in urlretrieve
>     with contextlib.closing(urlopen(url, data)) as fp:
>   File "/home/tails/anaconda3/envs/env37/lib/python3.7/urllib/request.py", line 222, in urlopen
>     return opener.open(url, data, timeout)
>   File "/home/tails/anaconda3/envs/env37/lib/python3.7/urllib/request.py", line 531, in open
>     response = meth(req, response)
>   File "/home/tails/anaconda3/envs/env37/lib/python3.7/urllib/request.py", line 641, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/home/tails/anaconda3/envs/env37/lib/python3.7/urllib/request.py", line 569, in error
>     return self._call_chain(*args)
>   File "/home/tails/anaconda3/envs/env37/lib/python3.7/urllib/request.py", line 503, in _call_chain
>     result = func(*args)
>   File "/home/tails/anaconda3/envs/env37/lib/python3.7/urllib/request.py", line 649, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 406: Not Acceptable

**Comment by tails1234** [comment]
The solution for me was to modify the get request so that a header is included with the request.

in "data_utils.py" in folder "MLwithTF"

edit line 13:
`from six.moves.urllib.request import urlretrieve`
to become this:
`from six.moves.urllib.request import urlretrieve, build_opener, install_opener`

after line 44 add this:
```
        opener = build_opener()
        opener.addheaders = [('user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36')]
        install_opener(opener)
```
